name: Unittest PR

on:
  pull_request:
    branches: [ main ]
    types: [ready_for_review, opened, reopened, synchronize]

jobs:
  run-test:
    runs-on: ubuntu-18.04
    name: Run tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch
          pip install .
      - name: Execute tests
        run: python -m pytest tests
